language: rust
after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
      deploy-docs.sh
env:
    global:
        secure: ScjGQukhCkaT+byasOZTLM6wqS7gnKGNAS9PrcfzKPXLVtQOY56O/caICsOyqCj2Ht4KvLtvbFDkhAgqsETJHuxIKUZJDmoyr+lKtO5qwbfqVc9Je/h0sEfr6KPxszUkPwrZrBfitwwLd8A/Rr71S/T75s1hKSoe4sQLzuxHH3qWWOGAP8vl1NHr4/UcuKwqYI6dzcCSEa3YTU1MR0VbBFIX/H0yGSagGI3olGQkOT9+knIKonK0Pz7z14QRJzrA69tf6jbFWlAIAmx/z0IS6oFPgHb3SggUdmN11wBO9zjtPuvSn9HqaXKNbvSHvubLjX2XsUwiZh6EcWi/8MlEeTEnX0esBDy6ENarnkcH0lYiMXTJVFRsJoaNP4Yb+5W4Pns2gWQ0VEPX2E5Q//li7V8Cqtg6y7sx3MgsvmoRHQwJeOEDIFX3LVhV+m0L0D6GGY/O4MO7HmVk5GLGW2XuCrTiEh5vypGMZ4Tme0aM3YnlXhnmHp3iRQshbYA8IZLK53If0ogfwmAYY/u6sfxUowbgQmezU2gKpa0AhGgGqubljXqfcjVHe1knbtFbDJObZjWeM00TPfOHfouUspj88mMlC7C7YOqbskHbhbGiqMPV5eVYTvoBmq8tJhJ9/bSgCEdxADjggHetOi3XU6QMbd3vunES13kmYRvFROMP6TE=
