language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - FEATURES=""
  - FEATURES="no_std"
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"